#!/usr/bin/env zsh

# 
# This file tests the vercmp function of pkg++.
# 

if [[ -z "$PKGMK_VERSION" ]]; then
	exec pkg++ $0
fi

function test_info {
	# 1 and 2: return and expected value
	# 3: Test number.
	# 4: Test name.
	(( $1 == $2 )) && \
		info "Test $3 worked. [$4]" || \
		error "Test $3 failed. [$4]"
}

vercmp "1.1" ">=" "1.2" || ! vercmp "1.2" ">=" "1.1"
test_info $? 1 1 "simple comp"

! vercmp "1.1" ">=" "1.1.3" && ! vercmp "1.1" "!=" "1.1.0"
test_info $? 0 2 "null values"

vercmp "1.1.1" "~>" "1.1" && ! vercmp "1.1.1" "~>" "1.2" && ! vercmp "1.3" "~>" "1.2"
test_info $? 0 3 "~> operator"

! vercmp "1.alpha" ">" "1.beta" && vercmp "1.beta" ">" "1.alpha"
test_info $? 0 4 "strings cmp"

vercmp "1-3" ">" "1-2"
test_info $? 0 5 "hyphens ver"

@{ "1.2" ">" "1.1" }@
test_info $? 0 6 "@{ function"

@{ "1. 2" ">" "1.1" }@ &>/dev/null
test_info $? 1 7 "@{ spaces  "

@{ 1.2.3 -ge 1.2.2 }@
test_info $? 0 8 "hyphen opts"

exit 0

