
PKGMK_PACKAGE_MANAGERS=(${PKGMK_PACKAGE_MANAGERS[@]} tazpkg)
# PKGMK_PM_NOARCH_SUPPORT=(${PKGMK_PM_NOARCH_SUPPORT[@]} tazpkg)

tazpkg:target () {
	if [[ "$version" = "devel" ]]; then
		echo "$PKGMK_PACKAGE_DIR/$pkgname-devel-${PKGMK_REVISION:=`date +%Y%m%d`}-$PKGMK_ARCH-$release.tazpkg"
	else
		echo "$PKGMK_PACKAGE_DIR/$pkgname-$version-$PKGMK_ARCH-$release.tazpkg"
	fi
}

tazpkg:build () {
	info "Building $TARGET."
	cd $PKG
	cat > $PKG/receipt <<EOF
# SliTaz package receipt.
# Generated by pkg++ with compliments to the chief.
PACKAGE="$name"
VERSION="$version"
CATEGORY="misc"
SHORT_DESC="$description"
WEB_SITE="$url"
MAINTAINER="$maintainer"
DEPENDS="${depends[@]}"
CONFIG_FILES="${config[@]}"
EOF
	{
		[[ -n "$description" ]] && echo "$description"
		[[ -n "$longdesc" ]]    && echo "$longdesc"
	} > $PKG/description.txt
	# FIXME: install-scripts
	tazpkg pack $PKG
	mv $PKG.tazpkg $TARGET
}

tazpkg:footprint () {
	warning "tazpkg footprints are not supported (for now)!"
}

tazpkg:install () {
	echo "tazpkg install ${PKGMK_INSTALL_ROOT:+-root=$PKGMK_INSTALL_ROOT} $TARGET"
}

